In [8]:
import pandas as pd
from sklearn import datasets
import sklearn.ensemble
!pip install xgboost

iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['target']= iris.target
from sklearn.model_selection import train_test_split

X_Tr, X_Te, Y_Tr, Y_Te = train_test_split(df.iloc[:,[0,1,2,3]], df.target
                                 , random_state=0
                                 , train_size=0.75)


In [15]:
import xgboost as xgb

dtrain = xgb.DMatrix(X_Tr, label=Y_Tr)
dtest = xgb.DMatrix(X_Te, label=Y_Te)

In [41]:
param = {
    'max_depth': 10,  # the maximum depth of each tree
    'eta': 0.3,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softmax',  # error evaluation for multiclass training
    'num_class': 3}  # the number of classes that exist in this datset
num_round = 100 

In [46]:
param2 = {
    'max_depth': 10,  # the maximum depth of each tree
    'eta': 0.3,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softprob',  # error evaluation for multiclass training
    'num_class': 3}  # the number of classes that exist in this datset
num_round = 100 

In [47]:
bst = xgb.train(param, dtrain, num_round)
bst2= xgb.train(param2, dtrain, num_round)
# bst.dump_model('dump.raw.txt')

[12:21:10] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[12:21:10] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [51]:
preds = bst.predict(dtest)
preds2=bst2.predict(dtest)

TypeError: len() takes no keyword arguments

In [57]:
print(preds)
print(preds2)

[2. 1. 0. 2. 0. 2. 0. 1. 1. 1. 2. 1. 1. 1. 1. 0. 1. 1. 0. 0. 2. 1. 0. 0.
 2. 0. 0. 1. 1. 0. 2. 1. 0. 2. 2. 1. 0. 2.]
[[2.3126563e-03 1.8249478e-03 9.9586236e-01]
 [2.8632625e-03 9.8282987e-01 1.4306889e-02]
 [9.8627716e-01 1.2601318e-02 1.1214638e-03]
 [6.0758920e-04 2.3367377e-03 9.9705565e-01]
 [9.9412113e-01 4.7484501e-03 1.1303829e-03]
 [9.3993550e-04 3.4520321e-03 9.9560803e-01]
 [9.9412113e-01 4.7484501e-03 1.1303829e-03]
 [7.9321285e-04 9.9747556e-01 1.7312156e-03]
 [7.5617136e-04 9.9576277e-01 3.4811294e-03]
 [9.1507466e-04 9.9487227e-01 4.2126607e-03]
 [5.9610065e-03 5.6688916e-02 9.3735003e-01]
 [7.9325971e-04 9.9753451e-01 1.6721624e-03]
 [9.1507466e-04 9.9487227e-01 4.2126607e-03]
 [7.5213856e-04 9.9045217e-01 8.7957317e-03]
 [9.1737224e-04 9.9737024e-01 1.7123356e-03]
 [9.9412113e-01 4.7484501e-03 1.1303829e-03]
 [2.3249709e-03 9.9130428e-01 6.3707661e-03]
 [5.5524837e-03 9.8904371e-01 5.4037711e-03]
 [9.9386901e-01 4.7472455e-03 1.3837226e-03]
 [9.9412113e-01 4.7484501e-0

In [38]:
import numpy as np
best_preds = np.asarray([np.argmax(line) for line in preds])

In [39]:
best_preds

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2], dtype=int64)

In [40]:
from sklearn.metrics import precision_score

print (precision_score(Y_Te, best_preds, average='macro'))

0.9666666666666667
